[tool.poetry]
name = "againstlolodds"
version = "0.1.0"
description = ""
authors = ["Noah Corona <noa@coronasoftware.net>"]

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.21"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
flake8 = "^3.7"

[tool.poetry.scripts]
start = "againstlolodds.main:start"
rift_explorer = "scripts:run_rift_explorer"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
